// <auto-generated />
using System;
using System.Text.Json;
using EcleticaBeerControl.Persistence.EF.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EcleticaBeerControl.Persistence.EF.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EcleticaBeerControl.Domain.Entities.Brewery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uuid")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Logo")
                        .HasColumnType("text")
                        .HasColumnName("logo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_breweries");

                    b.ToTable("breweries", (string)null);
                });

            modelBuilder.Entity("EcleticaBeerControl.Domain.Entities.Device", b =>
                {
                    b.Property<string>("Identifier")
                        .HasColumnType("text")
                        .HasColumnName("identifier");

                    b.Property<Guid>("BreweryId")
                        .HasColumnType("uuid")
                        .HasColumnName("brewery_id");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uuid")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Identifier")
                        .HasName("pk_devices");

                    b.HasIndex("BreweryId")
                        .HasDatabaseName("ix_devices_brewery_id");

                    b.HasIndex("Identifier")
                        .IsUnique()
                        .HasDatabaseName("ix_devices_identifier");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("EcleticaBeerControl.Domain.Entities.FermentationDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BreweryId")
                        .HasColumnType("uuid")
                        .HasColumnName("brewery_id");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uuid")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<string>("DeviceIdentifier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_identifier");

                    b.Property<JsonDocument>("FermentationProfile")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("fermentation_profile");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_fermentation_definitions");

                    b.HasIndex("BreweryId")
                        .HasDatabaseName("ix_fermentation_definitions_brewery_id");

                    b.HasIndex("DeviceIdentifier")
                        .HasDatabaseName("ix_fermentation_definitions_device_identifier");

                    b.ToTable("fermentation_definitions", (string)null);
                });

            modelBuilder.Entity("EcleticaBeerControl.Domain.Entities.FermentationProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BreweryId")
                        .HasColumnType("uuid")
                        .HasColumnName("brewery_id");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uuid")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<JsonDocument>("Steps")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("steps");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_fermentation_profiles");

                    b.HasIndex("BreweryId")
                        .HasDatabaseName("ix_fermentation_profiles_brewery_id");

                    b.ToTable("fermentation_profiles", (string)null);
                });

            modelBuilder.Entity("EcleticaBeerControl.Domain.Entities.FermentationSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BreweryId")
                        .HasColumnType("uuid")
                        .HasColumnName("brewery_id");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uuid")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("CurrentStepEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_step_end");

                    b.Property<DateTime?>("CurrentStepStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_step_start");

                    b.Property<string>("CurrentStepTitle")
                        .HasColumnType("text")
                        .HasColumnName("current_step_title");

                    b.Property<int?>("CurrentStepTotalDays")
                        .HasColumnType("integer")
                        .HasColumnName("current_step_total_days");

                    b.Property<int?>("CurrentTemperature")
                        .HasColumnType("integer")
                        .HasColumnName("current_temperature");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("DeviceIdentifier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_identifier");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int?>("TargetTemperature")
                        .HasColumnType("integer")
                        .HasColumnName("target_temperature");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_fermentation_sessions");

                    b.HasIndex("BreweryId")
                        .HasDatabaseName("ix_fermentation_sessions_brewery_id");

                    b.HasIndex("DeviceIdentifier")
                        .HasDatabaseName("ix_fermentation_sessions_device_identifier");

                    b.ToTable("fermentation_sessions", (string)null);
                });

            modelBuilder.Entity("EcleticaBeerControl.Domain.Entities.Device", b =>
                {
                    b.HasOne("EcleticaBeerControl.Domain.Entities.Brewery", "Brewery")
                        .WithMany()
                        .HasForeignKey("BreweryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_devices_breweries_brewery_id");

                    b.Navigation("Brewery");
                });

            modelBuilder.Entity("EcleticaBeerControl.Domain.Entities.FermentationDefinition", b =>
                {
                    b.HasOne("EcleticaBeerControl.Domain.Entities.Brewery", "Brewery")
                        .WithMany()
                        .HasForeignKey("BreweryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fermentation_definitions_breweries_brewery_id");

                    b.HasOne("EcleticaBeerControl.Domain.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fermentation_definitions_devices_device_id");

                    b.Navigation("Brewery");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("EcleticaBeerControl.Domain.Entities.FermentationProfile", b =>
                {
                    b.HasOne("EcleticaBeerControl.Domain.Entities.Brewery", "Brewery")
                        .WithMany()
                        .HasForeignKey("BreweryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fermentation_profiles_breweries_brewery_id");

                    b.Navigation("Brewery");
                });

            modelBuilder.Entity("EcleticaBeerControl.Domain.Entities.FermentationSession", b =>
                {
                    b.HasOne("EcleticaBeerControl.Domain.Entities.Brewery", "Brewery")
                        .WithMany()
                        .HasForeignKey("BreweryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fermentation_sessions_breweries_brewery_id");

                    b.HasOne("EcleticaBeerControl.Domain.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fermentation_sessions_devices_device_id");

                    b.Navigation("Brewery");

                    b.Navigation("Device");
                });
#pragma warning restore 612, 618
        }
    }
}
