name: Deploy EBC API

on:
  push:
    branches:
      - main
      - development
      - qa

jobs:
  build-and-deploy:
    permissions:
      contents: read
      packages: write
    uses: Autus-Solutions/autus-infra/.github/workflows/reusable-k8s-build-deploy.yml@main
    with:
      app_name: ebc-api
      namespace: ebl
      image_pull_secret_name: ghcr-pull-secret
    secrets: inherit
