name: Deploy Worker

on:
  workflow_dispatch:
  push:
    branches:
      - development

jobs:
  deploy:
    uses: Autus-Solutions/autus-infra/.github/workflows/reusable-k8s-build-deploy.yml@main
    with:
      app_name: ecletica-beer-control-worker
      namespace: ebl
      dockerfile: ./WorkerDockerfile
      context: .
      container_port: "80"
      enable_probes: "false"
      ingress_hosts: ""
      environment_name: production
      image_pull_secret_name: ghcr-pull-secret
    secrets:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
